Incbin "levels.lw"
Incbin "MouseMenu\frames\simple.png"
Incbin "MouseMenu\frames\volume.png"
Incbin "field.png"
Incbin "balls.png"
Incbin "MouseMenu\frames\panel.png"
Incbin "player.png"
Incbin "clock.png"
Incbin "background.jpg"
L_SetIncbin( True )
