Incbin "menu.lw"
Incbin "..\\menu\images\on_off.png"
Incbin "..\\menu\images\prev_track.png"
Incbin "..\\menu\images\play.png"
Incbin "..\\menu\images\next_track.png"
Incbin "..\\menu\images\repeat.png"
Incbin "images\close.png"
Incbin "..\\menu\frames\panel.png"
Incbin "..\\menu\frames\button.png"
Incbin "..\\menu\frames\menu_tab.png"
Incbin "..\\menu\frames\simple.png"
Incbin "..\\menu\frames\volume.png"
Incbin "..\\menu\frames\window.png"
Incbin "..\\menu\images\icons.png"
Incbin "..\\menu\images\combo_box.png"
Incbin "..\\menu\frames\window_title.png"
SetIncbin( True )
