Incbin "interface.lw"
Incbin "MouseMenu\frames\simple.png"
Incbin "MouseMenu\frames\volume.png"
Incbin "balls.png"
Incbin "MouseMenu\frames\panel.png"
Incbin "player.png"
Incbin "clock.png"
Incbin "background.jpg"
Incbin "MouseMenu\frames\button.png"
Incbin "MouseMenu\images\icons.png"
L_SetIncbin( True )
