Incbin "interface.lw"
Incbin "MouseMenu\frames\simple.png"
Incbin "MouseMenu\frames\volume.png"
Incbin "images\balls.png"
Incbin "MouseMenu\frames\panel.png"
Incbin "images\player.png"
Incbin "images\clock.png"
Incbin "images\background.jpg"
Incbin "MouseMenu\frames\button.png"
Incbin "MouseMenu\images\icons.png"
Incbin "MouseMenu\images\progressbar.png"
Incbin "images\fields.png"
L_SetIncbin( True )
